version: "3"
services:
  web:
    image: 373240450338.dkr.ecr.us-east-1.amazonaws.com/capstone_devops:latest
    # React by default uses ports 3000
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: ec2-tutorial
        awslogs-region: us-east-1
        awslogs-stream-prefix: web
